const router = require("express").Router();
const getAllCategories = require("./routeHandlers/categories/getAllCategories");
const getAllProducts = require("./routeHandlers/products/getAllProducts");
const getProductByName = require("./routeHandlers/products/getProductByName");
const getProductsBySalecount = require("./routeHandlers/products/getProductsBySalecount");
router.get("/allProducts", getAllProducts);
router.get("/products", getProductsBySalecount);
router.get("/allCategories", getAllCategories);
router.get("/products/:productName", getProductByName);
module.exports = router;
